# -*- coding: utf-8 -*-
"""Viet_request.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jIK4kDx1g105h4kk5Xh9YZEN733J27l5
"""

pip install bertopic

!pip install -U sentence-transformers huggingface-hub

import pandas as pd
import numpy as np
import re
from collections import Counter
#df = pd.read_csv('tong_hop_final_result_1.csv')
df = pd.read_excel('customer_contact.xlsx')
df.head()
df=pd.DataFrame(df['noidung'],columns=['noidung'])
df

stopwords=['và','những','có','vậy','không','gì','nên','ko','shop','cụ','thể','đã','hay','là','tới','được','thì','đây','mặc', 'buôn',
            'nhưng','rồi','k','quá','trời','ạ','thôi','như','z','đc','k','r','sao','z','hơi','v','mik','sốp','shop','á','hi','chúc']
# Define function to clean stopwords
def remove_stopwords(text):
    text = text.lower()
    words = re.findall(r'\b\w+\b', text)
    filtered = [word for word in words if word not in stopwords]
    return ' '.join(filtered)

# Apply to DataFrame column
df['noidung'] = df['noidung'].apply(remove_stopwords)

from huggingface_hub import login

login()

import os

token = os.getenv("HF_TOKEN")
print(f"Token: {token}")

from huggingface_hub import whoami

try:
    user_info = whoami(token=token)
    print(f"Authenticated user: {user_info}")
except Exception as e:
    print(f"Authentication error: {e}")

from sentence_transformers import SentenceTransformer

# Verify CUDA availability
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

try:
    model_name = "VoVanPhuc/sup-SimCSE-VietNamese-phobert-base"
    embedding_model = SentenceTransformer(model_name, device=device)
    print(f"Model '{model_name}' successfully loaded.")
except Exception as e:
    print(f"Error loading model: {e}")

pip install pyvi

# from sentence_transformers import SentenceTransformer
# from pyvi.ViTokenizer import tokenize

# df["Product_clean"] = df["noidung"].fillna("").astype(str)
# abstracts=df["Product_clean"]
# embedding_model = SentenceTransformer('VoVanPhuc/sup-SimCSE-VietNamese-phobert-base',device='cuda')
# # embedding_model = SentenceTransformer("VoVanPhuc/sup-SimCSE-VietNamese-phobert-base")

# embeddings = embedding_model.encode(
#       abstracts,
#     show_progress_bar=True # you can try 128 or more depending on GPU
# )
from pyvi.ViTokenizer import tokenize

# Assuming 'df' is already defined
df["Product_clean"] = df["noidung"].fillna("").astype(str)
abstracts = df["Product_clean"].tolist()

# Encode
embeddings = embedding_model.encode(
    abstracts,
    show_progress_bar=True
)

print(f"Embeddings shape: {embeddings.shape}")

from umap import UMAP
# We reduce the input embeddings from 384 dimensions to 5 dimensions
umap_model = UMAP(n_components=5, min_dist=0.0, n_neighbors=4, metric='cosine', random_state=42)

reduced_embeddings = umap_model.fit_transform(embeddings)

from hdbscan import HDBSCAN

hdbscan_model = HDBSCAN(
    min_cluster_size=5,  # try 300 → 800
    min_samples=3,        # more flexible
    metric="euclidean",    # stick to 'euclidean' if UMAP output is used
    cluster_selection_method="leaf"  # more fine-grained than 'eom'
)

clusters = hdbscan_model.fit_predict(reduced_embeddings)
len(set(clusters))

from sklearn.metrics import silhouette_score
print("Silhouette Score:", silhouette_score(reduced_embeddings, clusters))

def topic_differences(model, original_topics, nr_topics=5):
  df = pd.DataFrame(columns=["Topic", "Original", "Updated"])
  for topic in range(nr_topics):
# Extract top 5 words per topic per model
    og_words = " | ".join(list(zip(*original_topics[topic]))[0][:5])
    new_words = " | ".join(list(zip(*model.get_topic(topic)))[0][:5])
    df.loc[len(df)] = [topic, og_words, new_words]
  return df

from bertopic import BERTopic
from bertopic.representation import MaximalMarginalRelevance
from sentence_transformers import SentenceTransformer

# 1. Define your embedding model

# 2. Define your UMAP and HDBSCAN models (assuming you have these already)
# umap_model = ...
# hdbscan_model = ...

# 3. Create the representation model BEFORE creating BERTopic
mmr = MaximalMarginalRelevance(diversity=0.1)  # Use a lower diversity value

# 4. Create BERTopic with the representation model included from the start
new_topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    representation_model=mmr,  # Include it here directly
    language="multilingual",  # For Vietnamese support
    #min_topic_size=5,
    verbose=True
)

# 5. Fit the model once
topics, probs = new_topic_model.fit_transform(abstracts)


# 7. Check topic differences (assuming this is a custom function you have)
#topic_differences(new_topic_model, original_topics)

reduced_embeddings = UMAP(
n_components=2, min_dist=0.0, metric="cosine",n_neighbors=5, random_state=42
).fit_transform(embeddings)

# Save original representations
from copy import deepcopy
original_topics_2 = deepcopy(new_topic_model.topic_representations_)

from bertopic.representation import KeyBERTInspired
# Update our topic representations using KeyBERTInspired
representation_model = KeyBERTInspired()

new_topic_model.update_topics(abstracts, representation_model=representation_model)
# Show topic differences
topic_differences(new_topic_model, original_topics_2)

# Visualize topics and documents
fig = new_topic_model.visualize_documents(
abstracts,
reduced_embeddings=reduced_embeddings,
width=1200,
hide_annotations=True
)
# Update fonts of legend for easier visualization
fig.update_layout(font=dict(size=16))

!pip install llama-cpp-python

!wget https://huggingface.co/vilm/vinallama-7b-chat-GGUF/resolve/main/vinallama-7b-chat_q5_0.gguf

# from llama_cpp import Llama
# from bertopic import BERTopic
# from bertopic.representation import BaseRepresentation
# import pandas as pd

# # Load the GGUF model
# llm = Llama(
#     model_path="./vinallama-7b-chat_q5_0.gguf",
#     n_ctx=4096,
#     n_gpu_layers=35,
# )

# # Safe LLM wrapper
# def llama_response(text):
#     result = llm(text, max_tokens=50, temperature=0.7,top_p=0.7)
#     return result["choices"][0].get("text") or result["choices"][0].get("message", {}).get("content", "[NO OUTPUT]")

# # Prompt template
# prompt_template = """Tôi có một chủ đề bao gồm các tài liệu sau:
# [DOCUMENTS]
# Chủ đề này được mô tả bởi các từ khóa sau: '[KEYWORDS]'.
# Dựa trên các tài liệu và từ khóa, chủ đề này nói về điều gì?"""

# # Custom representation model class
# class CustomLlamaRepresentation(BaseRepresentation):
#     def __init__(self, llm_function, prompt_template, doc_length=50):
#         self.llm_function = llm_function
#         self.prompt_template = prompt_template
#         self.doc_length = doc_length

#     def transform(self, topic_info):
#         topic_representations = {}

#         for topic, info in topic_info.items():
#             if topic != -1:
#                 docs = "\n".join(info["docs"][:self.doc_length])
#                 keywords = ", ".join(info["keywords"])
#                 prompt = self.prompt_template.replace("[DOCUMENTS]", docs).replace("[KEYWORDS]", keywords)
#                 print(f"→ Generating topic {topic}...")
#                 response = self.llm_function(prompt)
#                 topic_representations[topic] = response.strip()

#         return topic_representations

# # Create custom representation model
# custom_repr = CustomLlamaRepresentation(
#     llm_function=llama_response,
#     prompt_template=prompt_template
# )

# # IMPORTANT: Generate text representations directly
# topic_info = new_topic_model.get_topic_info()
# topics = {topic: new_topic_model.get_topic(topic) for topic in topic_info.Topic.tolist() if topic != -1}
# topic_docs = new_topic_model.get_representative_docs()

# # Create topic_info dictionary as expected by the custom representation model
# info_dict = {}
# for topic_id in topics:
#     if topic_id != -1:
#         info_dict[topic_id] = {
#             "keywords": [word for word, _ in topics[topic_id]],
#             "docs": topic_docs.get(topic_id, [])
#         }

# # Generate text representations manually
# text_representations = custom_repr.transform(info_dict)

# # Create a custom visualization function
# def visualize_topic_representations(original_model, text_representations):
#     # Get original topics
#     original_topics = {
#         topic: [word for word, _ in original_model.get_topic(topic)]
#         for topic in original_model.get_topics() if topic != -1
#     }

#     # Create DataFrame for visualization
#     data = []
#     for topic_id in text_representations:
#         original_keywords = " | ".join(original_topics.get(topic_id, [])[:5])
#         text_repr = text_representations[topic_id]

#         data.append({
#             "Topic": topic_id,
#             "Original Keywords": original_keywords,
#             "Text Representation": text_repr
#         })

#     df = pd.DataFrame(data)
#     return df

# # Create visualization
# result_df = visualize_topic_representations(new_topic_model, text_representations)

# # Display results
# print(result_df)

# # Save to CSV for easier viewing if needed
# result_df.to_csv("topic_representations.csv", index=False)

# result_df

# from llama_cpp import Llama
# from bertopic.representation import BaseRepresentation
# # import pandas as pd
# # import concurrent.futures
# # import hashlib
# # import json
# # import os
# # from functools import lru_cache

# # # Cache directory
# # CACHE_DIR = "llm_cache"
# # os.makedirs(CACHE_DIR, exist_ok=True)

# # # Load the GGUF model with optimal parameters for speed
# # llm = Llama(
# #     model_path="./vinallama-7b-chat_q5_0.gguf",
# #     n_ctx=1024,  # Reduced context for speed
# #     n_gpu_layers=35,
# #     n_threads=1  # Adjust based on your CPU
# # )

# # # Cache function for LLM responses
# # def get_cache_path(prompt):
# #     # Create hash of prompt to use as filename
# #     prompt_hash = hashlib.md5(prompt.encode()).hexdigest()
# #     return os.path.join(CACHE_DIR, f"{prompt_hash}.json")

# # def cached_llama_response(prompt):
# #     cache_path = get_cache_path(prompt)

# #     # Check if response is already cached
# #     if os.path.exists(cache_path):
# #         with open(cache_path, 'r', encoding='utf-8') as f:
# #             return json.load(f)['response']

# #     # If not cached, generate response
# #     result = llm(
# #         prompt,
# #         max_tokens=50,
# #         temperature=0.5,
# #         top_p=0.5,
# #         top_k=40,       # Added for speed
# #         repeat_penalty=1.1  # Reduce repetition
# #     )
# #     response = result["choices"][0].get("text") or result["choices"][0].get("message", {}).get("content", "[NO OUTPUT]")

# #     # Cache the response
# #     with open(cache_path, 'w', encoding='utf-8') as f:
# #         json.dump({'prompt': prompt, 'response': response}, f)

# #     return response

# # # Function to process a single topic
# # def process_topic(topic_data):
# #     topic_id, info = topic_data
# #     if topic_id == -1:
# #         return None

# #     # Limit docs to a smaller number (5 instead of 20)
# #     docs = "\n".join(info["docs"][:5])
# #     keywords = ", ".join(info["keywords"])
# #     prompt = prompt_template.replace("[DOCUMENTS]", docs).replace("[KEYWORDS]", keywords)
# #     print(f"→ Generating topic {topic_id}...")
# #     response = cached_llama_response(prompt)
# #     return (topic_id, response.strip())

# # # Prompt template
# # prompt_template = """Tôi có một chủ đề bao gồm các tài liệu sau:
# # [DOCUMENTS]
# # Chủ đề này được mô tả bởi các từ khóa sau: '[KEYWORDS]'.
# # Dựa trên các tài liệu và từ khóa, chủ đề này nói về điều gì?"""

# # # Parallel processing version of the representation model
# # class FastLlamaRepresentation(BaseRepresentation):
# #     def __init__(self, llm_function, prompt_template, doc_length=5, max_workers=4):
# #         self.llm_function = llm_function
# #         self.prompt_template = prompt_template
# #         self.doc_length = doc_length
# #         self.max_workers = max_workers

# #     def transform(self, topic_info):
# #         topic_representations = {}

# #         # Prepare data for parallel processing
# #         topics_to_process = []
# #         for topic, info in topic_info.items():
# #             if topic != -1:
# #                 # Limit docs to improve speed
# #                 info_copy = info.copy()
# #                 info_copy["docs"] = info["docs"][:self.doc_length]
# #                 topics_to_process.append((topic, info_copy))

# #         # Process topics in parallel
# #         with concurrent.futures.ThreadPoolExecutor(max_workers=self.max_workers) as executor:
# #             results = executor.map(process_topic, topics_to_process)

# #             for result in results:
# #                 if result:
# #                     topic_id, response = result
# #                     topic_representations[topic_id] = response

# #         return topic_representations

# # # Create optimized representation model
# # fast_repr = FastLlamaRepresentation(
# #     llm_function=cached_llama_response,
# #     prompt_template=prompt_template,
# #     doc_length=10,  # Reduced from 20 to 5
# #     max_workers=4  # Adjust based on your CPU
# # )

# # # Generate topic info
# # print("Preparing topic information...")
# # topic_info = new_topic_model.get_topic_info()
# # topics = {topic: new_topic_model.get_topic(topic) for topic in topic_info.Topic.tolist() if topic != -1}
# # topic_docs = new_topic_model.get_representative_docs()

# # # Create topic_info dictionary optimized with fewer documents
# # info_dict = {}
# # for topic_id in topics:
# #     if topic_id != -1:
# #         info_dict[topic_id] = {
# #             "keywords": [word for word, _ in topics[topic_id]],
# #             "docs": topic_docs.get(topic_id, [])[:5]  # Limit to 5 documents per topic
# #         }

# # # Generate text representations with parallel processing
# # print("Generating topic representations...")
# # text_representations = fast_repr.transform(info_dict)

# # # Visualization function (same as before)
# # def visualize_topic_representations(original_model, text_representations):
# #     original_topics = {
# #         topic: [word for word, _ in original_model.get_topic(topic)]
# #         for topic in original_model.get_topics() if topic != -1
# #     }

# #     data = []
# #     for topic_id in text_representations:
# #         original_keywords = " | ".join(original_topics.get(topic_id, [])[:5])
# #         text_repr = text_representations[topic_id]

# #         data.append({
# #             "Topic": topic_id,
# #             "Original Keywords": original_keywords,
# #             "Text Representation": text_repr
# #         })

# #     df = pd.DataFrame(data)
# #     return df

# # # Create visualization
# # print("Creating visualization...")
# # result_df = visualize_topic_representations(new_topic_model, text_representations)

# # # Display results
# # print(result_df)

# # # Save to CSV for easier viewing
# # result_df.to_csv("topic_representations.csv", index=False)

from llama_cpp import Llama
from bertopic import BERTopic
from bertopic.representation import BaseRepresentation
import pandas as pd
import time
from tqdm import tqdm
import gc

# Load the GGUF model with Colab-friendly parameters
llm = Llama(
    model_path="./vinallama-7b-chat_q5_0.gguf",
    n_ctx=4096,
    n_gpu_layers=35,
    n_batch=128,  # Lower batch size to reduce memory usage
    n_threads=4,   # Moderate thread count for Colab
)

# Safe LLM wrapper with caching
_llama_cache = {}
def llama_response(text):
    # Check cache first
    if text in _llama_cache:
        return _llama_cache[text]

    # Run inference
    result = llm(text, max_tokens=50, temperature=0.8, top_p=0.8)
    response = result["choices"][0].get("text") or result["choices"][0].get("message", {}).get("content", "[NO OUTPUT]")

    # Cache result
    _llama_cache[text] = response
    return response

# Prompt template
prompt_template = """Tôi có một chủ đề bao gồm các tài liệu sau:
[DOCUMENTS]
Chủ đề này được mô tả bởi các từ khóa sau: '[KEYWORDS]'.
Dựa trên các tài liệu và từ khóa, chủ đề này nói về điều gì?"""

# Process a single topic with retry logic
def process_topic(topic_id, info, prompt_template, llm_function, max_retries=2):
    # Limit documents to reduce memory usage
    docs = "\n".join(info["docs"][:50])  # Reduced from 40 to 20
    keywords = ", ".join(info["keywords"])
    prompt = prompt_template.replace("[DOCUMENTS]", docs).replace("[KEYWORDS]", keywords)

    for attempt in range(max_retries + 1):
        try:
            response = llm_function(prompt)
            return response.strip()
        except Exception as e:
            if attempt < max_retries:
                time.sleep(1)  # Short delay before retry
            else:
                return f"[ERROR: {str(e)}]"

# Improved memory management for topic processing
def process_topics_in_batches(topic_info, prompt_template, llm_function, batch_size=5):
    topic_representations = {}
    topic_ids = [topic for topic in topic_info.keys() if topic != -1]

    # Process topics in small batches to manage memory
    for i in range(0, len(topic_ids), batch_size):
        batch = topic_ids[i:i+batch_size]

        for topic_id in tqdm(batch, desc=f"Batch {i//batch_size + 1}/{(len(topic_ids) + batch_size - 1)//batch_size}"):
            response = process_topic(
                topic_id,
                topic_info[topic_id],
                prompt_template,
                llm_function
            )
            topic_representations[topic_id] = response

        # Force garbage collection between batches
        gc.collect()

    return topic_representations

# Custom representation model class
class CustomLlamaRepresentation(BaseRepresentation):
    def __init__(self, llm_function, prompt_template, doc_length=20):
        self.llm_function = llm_function
        self.prompt_template = prompt_template
        self.doc_length = doc_length

    def transform(self, topic_info):
        return process_topics_in_batches(
            topic_info,
            self.prompt_template,
            self.llm_function
        )

# Create custom representation model
custom_repr = CustomLlamaRepresentation(
    llm_function=llama_response,
    prompt_template=prompt_template
)

# Helper function to prepare topic info with memory optimizations
def prepare_topic_info(model):
    topic_info = model.get_topic_info()
    topics = {topic: model.get_topic(topic) for topic in topic_info.Topic.tolist() if topic != -1}
    topic_docs = model.get_representative_docs()

    # Create topic_info dictionary
    info_dict = {}
    for topic_id in topics:
        if topic_id != -1:
            # Limit keywords to save memory
            info_dict[topic_id] = {
                "keywords": [word for word, _ in topics[topic_id]][:10],  # Limit to top 10 keywords
                "docs": topic_docs.get(topic_id, [])[:20]  # Limit to top 20 documents
            }

    return info_dict

# Create a custom visualization function
def visualize_topic_representations(original_model, text_representations):
    # Get original topics (doing this once and reusing)
    original_topics = {}
    for topic in original_model.get_topics():
        if topic != -1:
            original_topics[topic] = [word for word, _ in original_model.get_topic(topic)][:5]

    # Create DataFrame for visualization
    data = []
    for topic_id in text_representations:
        original_keywords = " | ".join(original_topics.get(topic_id, []))
        text_repr = text_representations[topic_id]

        data.append({
            "Topic": topic_id,
            "Original Keywords": original_keywords,
            "Text Representation": text_repr
        })

    return pd.DataFrame(data)

# Main function with improved memory management
def generate_topic_representations(topic_model):
    start_time = time.time()

    # Prepare topic info
    print("Preparing topic information...")
    info_dict = prepare_topic_info(topic_model)

    # Force garbage collection before starting inference
    gc.collect()

    # Generate text representations with batching
    print(f"Generating text representations for {len(info_dict)} topics...")
    text_representations = custom_repr.transform(info_dict)

    # Create visualization
    result_df = visualize_topic_representations(topic_model, text_representations)

    # Display timing information
    elapsed = time.time() - start_time
    print(f"Process completed in {elapsed:.2f} seconds")

    # Save to CSV for easier viewing
    result_df.to_csv("topic_representations.csv", index=False)

    return result_df

# Example usage:
result_df = generate_topic_representations(new_topic_model)
print(result_df)

result_df.to_csv("topic_representations_fast.csv", index=False)

